Migrate to library
MobileRoboticsSkoltech/twist-n-sync pull request #16
Opened 2021-08-04 14:55 UTC by pmokeev

2021-08-05 11:56 UTC, samorojy commented
После осознания этого кода моя жизнь стала лучше

2021-08-05 17:51 UTC, anastasiia-kornilova requested changes

2021-08-05 17:51 UTC, anastasiia-kornilova commented on .gitignore
> +app/src/main/cpp/generated/bridge/cs
Let's add everything from "generated" to .gitignore? Anyway, it will be re-generated every time.

2021-08-05 17:51 UTC, anastasiia-kornilova commented on .gitmodules
> +[submodule "app/src/main/cpp/lib/spline"]
Why do we need this, if Arthur was migrating to FetchContent?

2021-08-05 17:51 UTC, anastasiia-kornilova commented on app/build.gradle
> +                arguments "-DANDROID_ARM_NEON=FALSE"
Are you sure that we would like to keep it disabled in final version?

2021-08-05 17:51 UTC, anastasiia-kornilova commented on app/src/main/cpp/CMakeLists.txt
> +        source
Let's call this folder in more clear way -- like "twist-n-sync-cpp"

2021-08-05 17:51 UTC, anastasiia-kornilova commented on app/src/main/cpp/CMakeLists.txt
> +set(SCAPIX_PLATFORM "windows" CACHE STRING "one of the folders inside 'source/chat/platform': android, windows")
What windows means in this context?

2021-08-05 17:51 UTC, anastasiia-kornilova commented on app/src/main/cpp/generated/bridge/java/TimeSync.cpp
> +// Generated by Scapix Language Bridge
Those files should not be there

2021-08-05 17:51 UTC, anastasiia-kornilova commented on app/src/main/cpp/source/TimeSync.cpp
> +//
To be updated with License

2021-08-12 11:08 UTC, pmokeev commented on app/build.gradle
> +                arguments "-DANDROID_ARM_NEON=FALSE"
No, I'm not sure. Due to the fact that the difference between True / False is not that big, I do not think that it matters. But I changed to True :)

2021-08-12 11:09 UTC, pmokeev commented on app/src/main/cpp/CMakeLists.txt
> +set(SCAPIX_PLATFORM "windows" CACHE STRING "one of the folders inside 'source/chat/platform': android, windows")
I created an [issue](https://github.com/scapix-com/scapix/issues/26) in the developer's repository on this topic, because I also do not quite understand what this function is responsible for. As soon as he answers, I will correct this line.

2021-08-12 17:03 UTC, anastasiia-kornilova requested changes
The final step -- please, add library license to the source tree.

2021-08-12 17:05 UTC, anastasiia-kornilova commented on app/src/main/cpp/CMakeLists.txt
> +include_directories(bridge PUBLIC ${eigen_SOURCE_DIR})
Let's add this to "populate" if section, they are very related.

2021-09-01 16:23 UTC, azaat approved these changes

2021-09-01 16:23 UTC, merged